name: Build and Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  notepadqq:
    runs-on: ubuntu-latest
    steps:   
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: false
          file: {context}/build.Dockerfile
