name: Build and Test CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  notepadqq:
    runs-on: ubuntu-latest
    steps:   
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: false
        file: build.Dockerfile
